apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31000
      targetPort: 80
      name: http
  selector:
    app: vote-deployment
